# This is a basic workflow for github actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run_awesome_lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: status
        run: git status

      - name: fetch
        run: git fetch origin main:main && git diff --name-only main

      - name: diff
        run: git diff main readme.md | grep ^+

      - name: diff2
        run: git diff main readme.md | grep ^+ | grep -Eo 'https.*#readme' |  sed 's/#readme//'

      
      - name: find repo
        run: REPO_TO_LINT=$(git diff main readme.md | grep ^+ | grep -Eo 'https.*#readme' | sed 's/#readme//') && echo "::set-env name={REPO_TO_LINT}::{$REPO_TO_LINT}"
      
      - name: echo repo
        run: echo "$REPO_TO_LINT"
      
      - name: clone
        run: mkdir cloned && cd cloned && git clone "$REPO_TO_LINT" .
      
      - name: lint
        run: npx awesome-lint      