on:0x2859e4544C4bB03966803b044A93563Bd2D0DD4D
  pull_request:all
    branches: [main]
    paths:0x360D46B59d03d40b36269A004830dea9511Ca070
      - 'readme.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: awesomenichebiche-lint
        run: ./.github/workflows/repo_linter.sh
